[2025-06-29 12:40:30,728: INFO: common: yaml file :config\config.yaml loaded_successfully]
[2025-06-29 12:40:58,497: INFO: common: yaml file :config\config.yaml loaded_successfully]
[2025-06-29 12:40:58,512: INFO: common: yaml file :params.yaml loaded_successfully]
[2025-06-29 12:40:58,512: INFO: common: created direactory as :artifacts]
[2025-06-29 12:40:58,519: INFO: common: created direactory as :artifacts/data_ingestion]
[2025-06-29 12:43:07,018: INFO: common: yaml file :config\config.yaml loaded_successfully]
[2025-06-29 12:43:07,018: INFO: common: yaml file :params.yaml loaded_successfully]
[2025-06-29 12:43:07,026: INFO: common: created direactory as :artifacts]
[2025-06-29 12:43:07,033: INFO: common: created direactory as :artifacts/data_ingestion]
[2025-06-29 12:43:13,422: INFO: 2528595678: File is downloaded]
[2025-06-29 13:12:48,168: INFO: main: Stage Data Ingestion stage initiated]
[2025-06-29 13:12:48,168: INFO: common: yaml file :config\config.yaml loaded_successfully]
[2025-06-29 13:12:48,168: INFO: common: yaml file :params.yaml loaded_successfully]
[2025-06-29 13:12:48,168: INFO: common: created direactory as :artifacts]
[2025-06-29 13:12:48,176: INFO: common: created direactory as :artifacts/data_ingestion]
[2025-06-29 13:12:53,122: INFO: data_ingestion: File is downloaded]
[2025-06-29 13:12:53,457: INFO: main: Stage Data Ingestion stage Completed]
[2025-06-29 14:14:25,812: INFO: config: PyTorch version 2.7.1 available.]
[2025-06-29 15:25:55,059: INFO: config: PyTorch version 2.7.1 available.]
[2025-06-29 15:26:04,894: INFO: common: yaml file :config\config.yaml loaded_successfully]
[2025-06-29 15:26:04,919: INFO: common: yaml file :params.yaml loaded_successfully]
[2025-06-29 15:26:04,926: INFO: common: created direactory as :artifacts]
[2025-06-29 15:26:40,674: INFO: common: yaml file :config\config.yaml loaded_successfully]
[2025-06-29 15:26:40,685: INFO: common: yaml file :params.yaml loaded_successfully]
[2025-06-29 15:26:40,689: INFO: common: created direactory as :artifacts]
[2025-06-29 15:26:40,692: INFO: common: created direactory as :artifacts/data_transformation]
[2025-06-29 15:27:32,280: INFO: common: yaml file :config\config.yaml loaded_successfully]
[2025-06-29 15:27:32,286: INFO: common: yaml file :params.yaml loaded_successfully]
[2025-06-29 15:27:32,289: INFO: common: created direactory as :artifacts]
[2025-06-29 15:27:32,295: INFO: common: created direactory as :artifacts/data_transformation]
[2025-06-29 15:29:40,873: INFO: common: yaml file :config\config.yaml loaded_successfully]
[2025-06-29 15:29:40,879: INFO: common: yaml file :params.yaml loaded_successfully]
[2025-06-29 15:29:40,883: INFO: common: created direactory as :artifacts]
[2025-06-29 15:29:40,883: INFO: common: created direactory as :artifacts/data_transformation]
[2025-06-29 15:30:51,508: INFO: common: yaml file :config\config.yaml loaded_successfully]
[2025-06-29 15:30:51,515: INFO: common: yaml file :params.yaml loaded_successfully]
[2025-06-29 15:30:51,520: INFO: common: created direactory as :artifacts]
[2025-06-29 15:30:51,521: INFO: common: created direactory as :artifacts/data_transformation]
[2025-06-29 15:31:03,380: INFO: common: yaml file :config\config.yaml loaded_successfully]
[2025-06-29 15:31:03,386: INFO: common: yaml file :params.yaml loaded_successfully]
[2025-06-29 15:31:03,389: INFO: common: created direactory as :artifacts]
[2025-06-29 15:31:03,393: INFO: common: created direactory as :artifacts/data_transformation]
[2025-06-29 15:33:25,612: INFO: common: yaml file :config\config.yaml loaded_successfully]
[2025-06-29 15:33:25,616: INFO: common: yaml file :params.yaml loaded_successfully]
[2025-06-29 15:33:25,620: INFO: common: created direactory as :artifacts]
[2025-06-29 15:33:25,623: INFO: common: created direactory as :artifacts/data_transformation]
[2025-06-29 15:33:37,635: INFO: common: yaml file :config\config.yaml loaded_successfully]
[2025-06-29 15:33:37,641: INFO: common: yaml file :params.yaml loaded_successfully]
[2025-06-29 15:33:37,645: INFO: common: created direactory as :artifacts]
[2025-06-29 15:33:37,647: INFO: common: created direactory as :artifacts/data_transformation]
[2025-06-29 15:35:17,476: INFO: common: yaml file :config\config.yaml loaded_successfully]
[2025-06-29 15:35:17,480: INFO: common: yaml file :params.yaml loaded_successfully]
[2025-06-29 15:35:17,480: INFO: common: created direactory as :artifacts]
[2025-06-29 15:35:17,493: INFO: common: created direactory as :artifacts/data_transformation]
[2025-06-30 23:45:27,525: INFO: config: PyTorch version 2.7.1 available.]
[2025-06-30 23:45:31,065: INFO: main: Stage Data Ingestion stage initiated]
[2025-06-30 23:45:31,071: INFO: common: yaml file :config\config.yaml loaded_successfully]
[2025-06-30 23:45:31,086: INFO: common: yaml file :params.yaml loaded_successfully]
[2025-06-30 23:45:31,091: INFO: common: created direactory as :artifacts]
[2025-06-30 23:45:31,091: INFO: common: created direactory as :artifacts/data_ingestion]
[2025-06-30 23:45:31,092: INFO: data_ingestion: File already exists]
[2025-06-30 23:45:31,318: INFO: main: Stage Data Ingestion stage Completed]
[2025-06-30 23:45:31,318: INFO: main: Stage Data Transformation stage initiated]
[2025-06-30 23:45:31,318: INFO: common: yaml file :config\config.yaml loaded_successfully]
[2025-06-30 23:45:31,318: INFO: common: yaml file :params.yaml loaded_successfully]
[2025-06-30 23:45:31,318: INFO: common: created direactory as :artifacts]
[2025-06-30 23:45:31,318: INFO: common: created direactory as :artifacts/data_transformation]
[2025-06-30 23:45:57,905: INFO: main: Stage Data Transformation stage Completed]
[2025-07-01 00:17:17,809: INFO: config: PyTorch version 2.7.1 available.]
[2025-07-01 01:23:18,018: INFO: server: Started server process [15528]]
[2025-07-01 01:23:18,034: INFO: on: Waiting for application startup.]
[2025-07-01 01:23:18,034: INFO: on: Application startup complete.]
[2025-07-01 01:23:18,034: INFO: server: Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)]
[2025-07-01 01:24:53,773: INFO: common: yaml file :config\config.yaml loaded_successfully]
[2025-07-01 01:24:53,789: INFO: common: yaml file :params.yaml loaded_successfully]
[2025-07-01 01:24:53,789: INFO: common: created direactory as :artifacts]
[2025-07-01 01:24:53,789: INFO: common: created direactory as :artifacts/model_evaluation]
[2025-07-01 01:24:53,789: ERROR: h11_impl: Exception in ASGI application
]
Traceback (most recent call last):
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\utils\hub.py", line 470, in cached_files
    hf_hub_download(
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'artifacts/model_trainer/tokenizer'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\MLOPS_TextSummarizer\app.py", line 33, in predict_route
    raise e
  File "D:\MLOPS_TextSummarizer\app.py", line 30, in predict_route
    text=obj.predict(text)
  File "D:\MLOPS_TextSummarizer\src\textSummarizer\pipeline\predicition_pipeline.py", line 13, in predict
    tokenizer = AutoTokenizer.from_pretrained(self.config.tokenizer_path)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 982, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 814, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\utils\hub.py", line 312, in cached_file
    file = cached_files(path_or_repo_id=path_or_repo_id, filenames=[filename], **kwargs)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\utils\hub.py", line 522, in cached_files
    resolved_files = [
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\utils\hub.py", line 523, in <listcomp>
    _get_cache_file_to_return(path_or_repo_id, filename, cache_dir, revision) for filename in full_filenames
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\utils\hub.py", line 140, in _get_cache_file_to_return
    resolved_file = try_to_load_from_cache(path_or_repo_id, full_filename, cache_dir=cache_dir, revision=revision)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'artifacts/model_trainer/tokenizer'. Use `repo_type` argument if needed.
[2025-07-01 01:25:00,687: INFO: common: yaml file :config\config.yaml loaded_successfully]
[2025-07-01 01:25:00,687: INFO: common: yaml file :params.yaml loaded_successfully]
[2025-07-01 01:25:00,687: INFO: common: created direactory as :artifacts]
[2025-07-01 01:25:00,687: INFO: common: created direactory as :artifacts/model_evaluation]
[2025-07-01 01:25:00,706: ERROR: h11_impl: Exception in ASGI application
]
Traceback (most recent call last):
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\utils\hub.py", line 470, in cached_files
    hf_hub_download(
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'artifacts/model_trainer/tokenizer'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\MLOPS_TextSummarizer\app.py", line 33, in predict_route
    raise e
  File "D:\MLOPS_TextSummarizer\app.py", line 30, in predict_route
    text=obj.predict(text)
  File "D:\MLOPS_TextSummarizer\src\textSummarizer\pipeline\predicition_pipeline.py", line 13, in predict
    tokenizer = AutoTokenizer.from_pretrained(self.config.tokenizer_path)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 982, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 814, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\utils\hub.py", line 312, in cached_file
    file = cached_files(path_or_repo_id=path_or_repo_id, filenames=[filename], **kwargs)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\utils\hub.py", line 522, in cached_files
    resolved_files = [
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\utils\hub.py", line 523, in <listcomp>
    _get_cache_file_to_return(path_or_repo_id, filename, cache_dir, revision) for filename in full_filenames
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\utils\hub.py", line 140, in _get_cache_file_to_return
    resolved_file = try_to_load_from_cache(path_or_repo_id, full_filename, cache_dir=cache_dir, revision=revision)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'artifacts/model_trainer/tokenizer'. Use `repo_type` argument if needed.
[2025-07-01 01:26:31,091: INFO: common: yaml file :config\config.yaml loaded_successfully]
[2025-07-01 01:26:31,091: INFO: common: yaml file :params.yaml loaded_successfully]
[2025-07-01 01:26:31,091: INFO: common: created direactory as :artifacts]
[2025-07-01 01:26:31,091: INFO: common: created direactory as :artifacts/model_evaluation]
[2025-07-01 01:26:31,091: ERROR: h11_impl: Exception in ASGI application
]
Traceback (most recent call last):
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\utils\hub.py", line 470, in cached_files
    hf_hub_download(
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'artifacts/model_trainer/tokenizer'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\MLOPS_TextSummarizer\app.py", line 33, in predict_route
    raise e
  File "D:\MLOPS_TextSummarizer\app.py", line 30, in predict_route
    text=obj.predict(text)
  File "D:\MLOPS_TextSummarizer\src\textSummarizer\pipeline\predicition_pipeline.py", line 13, in predict
    tokenizer = AutoTokenizer.from_pretrained(self.config.tokenizer_path)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 982, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 814, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\utils\hub.py", line 312, in cached_file
    file = cached_files(path_or_repo_id=path_or_repo_id, filenames=[filename], **kwargs)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\utils\hub.py", line 522, in cached_files
    resolved_files = [
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\utils\hub.py", line 523, in <listcomp>
    _get_cache_file_to_return(path_or_repo_id, filename, cache_dir, revision) for filename in full_filenames
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\utils\hub.py", line 140, in _get_cache_file_to_return
    resolved_file = try_to_load_from_cache(path_or_repo_id, full_filename, cache_dir=cache_dir, revision=revision)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'artifacts/model_trainer/tokenizer'. Use `repo_type` argument if needed.
[2025-07-01 01:26:57,389: INFO: common: yaml file :config\config.yaml loaded_successfully]
[2025-07-01 01:26:57,395: INFO: common: yaml file :params.yaml loaded_successfully]
[2025-07-01 01:26:57,397: INFO: common: created direactory as :artifacts]
[2025-07-01 01:26:57,398: INFO: common: created direactory as :artifacts/model_evaluation]
[2025-07-01 01:26:57,401: ERROR: h11_impl: Exception in ASGI application
]
Traceback (most recent call last):
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\utils\hub.py", line 470, in cached_files
    hf_hub_download(
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'artifacts/model_trainer/tokenizer'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\MLOPS_TextSummarizer\app.py", line 33, in predict_route
    raise e
  File "D:\MLOPS_TextSummarizer\app.py", line 30, in predict_route
    text=obj.predict(text)
  File "D:\MLOPS_TextSummarizer\src\textSummarizer\pipeline\predicition_pipeline.py", line 13, in predict
    tokenizer = AutoTokenizer.from_pretrained(self.config.tokenizer_path)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 982, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 814, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\utils\hub.py", line 312, in cached_file
    file = cached_files(path_or_repo_id=path_or_repo_id, filenames=[filename], **kwargs)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\utils\hub.py", line 522, in cached_files
    resolved_files = [
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\utils\hub.py", line 523, in <listcomp>
    _get_cache_file_to_return(path_or_repo_id, filename, cache_dir, revision) for filename in full_filenames
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\transformers\utils\hub.py", line 140, in _get_cache_file_to_return
    resolved_file = try_to_load_from_cache(path_or_repo_id, full_filename, cache_dir=cache_dir, revision=revision)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\MLOPS_TextSummarizer\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'artifacts/model_trainer/tokenizer'. Use `repo_type` argument if needed.
[2025-07-01 01:28:12,984: INFO: server: Shutting down]
[2025-07-01 01:28:13,090: INFO: on: Waiting for application shutdown.]
[2025-07-01 01:28:13,094: INFO: on: Application shutdown complete.]
[2025-07-01 01:28:13,096: INFO: server: Finished server process [15528]]
